version: "3.7"

services:
    
    postgres:
        container_name: postgres-container
        image: library/postgres:9.6-alpine
        ports: 
            - "5431:5432"
        volumes: 
            - ./docker/postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root@123
            - POSTGRES_DB=database
        restart: always
        tty: true