version: "3.7"

services:
  api:
    container_name: "api-container"
    image: node:10.16-slim
    working_dir: /backend/src/
    volumes:
      - ./:/backend/src/
    ports: 
      - "3333:3333"
    command: >
      bash -c "npm install 
      && npm run start"
    environment:
      - DB_URI=postgres
    depends_on: 
      - postgres

  postgres:
    container_name: postgres-container
    image: library/postgres:9.6-alpine
    ports: 
      - "5431:5432"
    volumes: 
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root@123
      - POSTGRES_DB=database
    restart: always
